name: build-and-push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        id: set_tag
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
          echo "image_tag=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Image tag: $SHORT_SHA"

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gitomyapp:${{ env.IMAGE_TAG }} .

      - name: Save Docker Image
        run: docker save ${{ secrets.DOCKER_USERNAME }}/gitomyapp:${{ env.IMAGE_TAG }} -o image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 1

  push:
    runs-on: ubuntu-latest
    needs: [build]
    environment: testing

    steps:
      - name: Set image tag from build
        run: echo "IMAGE_TAG=${{ needs.build.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gitomyapp:${{ env.IMAGE_TAG }}

      - name: Push completed
        run: 'echo "Push completed - Image tag: ${{ env.IMAGE_TAG }}"'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, push]
    environment: testing

    steps:
      - name: Set image tag from build
        run: echo "IMAGE_TAG=${{ needs.build.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/gitomyapp:.*|image: ${{ secrets.DOCKER_USERNAME }}/gitomyapp:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml

      - name: Verify changes
        run: cat k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "Nordine GRASSA"
          git config --global user.email "ngrassa@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/gitomyapp:${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push

      - name: Deploy completed
        run: 'echo "Manifests updated with latest tag: ${{ env.IMAGE_TAG }}"'