name: build-and-push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Set up job
        uses: actions/checkout@v4

      - name: Pulling Git Repo
        run: echo "Repository cloned successfully"

      - name: Test Docker Installation
        run: |
          docker --version
          docker info

      - name: List files
        run: |
          ls -la
          cat Dockerfile

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gitomyapp:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gitomyapp:latest

      - name: Noureddine GRASSA
        run: echo "Build and push completed by Noureddine GRASSA"